name: 'Setup on Windows'
description: 'Installs dependencies specific to Windows'
inputs:
  codec-aom:
    description: 'Can take the values: OFF, LOCAL, SYSTEM'
    default: 'OFF'
  codec-dav1d:
    description: 'Can take the values: OFF, LOCAL, SYSTEM'
    default: 'OFF'
  codec-rav1e:
    description: 'Can take the values: OFF, LOCAL, SYSTEM'
    default: 'OFF'
  extra-cache-key:
    description: 'Extra cache key to use in the cache name. Useful when several caches are used in one workflow.'
    default: ''
outputs:
  ext-cache-hit:
    value: ${{ steps.cache.outputs.ext-cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Setup Visual Studio shell
      uses: egor-tensin/vs-shell@9a932a62d05192eae18ca370155cf877eecc2202 # v2.1
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      if: ${{ inputs.codec-dav1d == 'LOCAL' }}
      id: vcpkg
      with:
        pkgs: vcpkg-tool-meson
        triplet: x64-windows-release
        token: ${{ github.token }}
        github-binarycache: true
        cache-key: ${{ hashFiles('cmake/Modules/*', 'ext/*.cmd', 'ext/*.sh') }}

    - uses: ./.github/actions/setup-common
      with:
        codec-aom: ${{ inputs.codec-aom }}
        codec-dav1d: ${{ inputs.codec-dav1d }}
        codec-rav1e: ${{ inputs.codec-rav1e }}
    - uses: ./.github/actions/cache
      id: cache
      with:
        extra-key: ${{ inputs.extra-cache-key }}
        use-rust: ${{ inputs.codec-rav1e == 'LOCAL' }}
